import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "@/context";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FixedContact from "./components/FixedContact";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          <GlobalState>
            <Navbar />
            {children}
            <Footer />
            <FixedContact />
          </GlobalState>
        </Suspense>
      </body>
    </html>
  );
}
